set_property SRC_FILE_INFO {cfile:{C:/Users/jawoo/Desktop/Logic/DL202010_Woods/Lab11_guess/Lab11_guess.srcs/constrs_1/imports/Lab 10/led.xdc} rfile:{../../../Lab11_guess.srcs/constrs_1/imports/Lab 10/led.xdc} id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/jawoo/Desktop/Logic/DL202010_Woods/Lab11_guess/Lab11_guess.srcs/constrs_1/imports/Lab 10/btnC.xdc} rfile:{../../../Lab11_guess.srcs/constrs_1/imports/Lab 10/btnC.xdc} id:2} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/jawoo/Desktop/Logic/DL202010_Woods/Lab11_guess/Lab11_guess.srcs/constrs_1/imports/Lab 10/btnD.xdc} rfile:{../../../Lab11_guess.srcs/constrs_1/imports/Lab 10/btnD.xdc} id:3} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/jawoo/Desktop/Logic/DL202010_Woods/Lab11_guess/Lab11_guess.srcs/constrs_1/imports/Lab 10/btnU.xdc} rfile:{../../../Lab11_guess.srcs/constrs_1/imports/Lab 10/btnU.xdc} id:4} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/jawoo/Desktop/Logic/DL202010_Woods/Lab11_guess/Lab11_guess.srcs/constrs_1/imports/Lab 10/clock.xdc} rfile:{../../../Lab11_guess.srcs/constrs_1/imports/Lab 10/clock.xdc} id:5} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/jawoo/Desktop/Logic/DL202010_Woods/Lab11_guess/Lab11_guess.srcs/constrs_1/imports/Lab11_guess/btnL.xdc rfile:../../../Lab11_guess.srcs/constrs_1/imports/Lab11_guess/btnL.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/jawoo/Desktop/Logic/DL202010_Woods/Lab11_guess/Lab11_guess.srcs/constrs_1/imports/Lab11_guess/btnR.xdc rfile:../../../Lab11_guess.srcs/constrs_1/imports/Lab11_guess/btnR.xdc id:7} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports btnC]
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports btnD]
set_property src_info {type:XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports btnU]
set_property src_info {type:XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports btnL]
set_property src_info {type:XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports btnR]
